server:
  port: 8080
spring:
  application:
    name: "Reports"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
aws:
  dynamodb:
    endpoint: "http://localhost:8000"
adapter:
  sqs:
    region: "us-east-1"
    queueUrl: "http://localhost:4566/000000000000/sample"
    endpoint: "http://localhost:4566 # For localstack only"
