cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: ${SPRING_URI_JWT:http://localhost:8080/.well-known/jwks.json}

aws:
  region: ${AWS_REGION:us-east-2}

entrypoint:
  sqs:
    region: ${AWS_REGION:us-east-2}
    queueUrl: ${AWS_SQS_QUEUE_URL_REPORT:http://localhost:4566/000000000000/sample}
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1