#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

aws:
  region: "us-east-2"
#  dynamodb:

entrypoint:
  sqs:
    region: "us-east-2"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/328764941205/REPORT"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1